config/routes.rb
Rails.application.routes.draw do
  root to: 'buffets#index'
  
  devise_for :customers, controllers: {
    registrations: 'customers/registrations'
  }
  
  devise_for :buffet_owners

  resources :buffets, only: [:edit, :update, :show, :create, :new, :index] do
    resources :rates, only: [:show, :new, :create, :index]
    member do
      post :disable
      post :activate
    end
    get :search, on: :collection
  end

  resources :rates, only: [] do
    resources :holder_images, only: [:create]
  end

  resources :events, only: [:edit, :update, :show, :create, :new, :index] do
    resources :event_prices, only: [:edit, :update, :new, :create]
    resources :orders, only: [:new, :create]
    resources :holder_images, only: [:create, :destroy]
    member do
      post :disable
      post :activate
      post :cover
    end
  end

  resources :orders, only: [:show, :index] do
    resources :messages, only: [:create]
    resources :service_proposals, only: [:create, :update]
    member do
      post :accept_proposal
      post :reject_proposal
      post :cancel
    end
  end

  namespace :api do
    namespace :v1 do
      resources :buffets, only: [:show, :index] do
        resources :events, only: [:index] do
          get :availability, on: :member
        end
      end
    end
  end
end

app/models/buffet.rb
class Buffet < ApplicationRecord
  belongs_to :buffet_owner
  has_many :events
  has_many :holder_images, through: :events
  has_many :orders, through: :events
  has_many :messages, as: :user
  has_many :rates
  has_many :buffet_payment_methods
  has_many :payment_methods, through: :buffet_payment_methods

  validates :brand_name, :corporate_name, :phone_number, :registration,
            :email, :address, :district, :city, :state_code, :zip_code,
            :description, presence: true
  validates :brand_name, :corporate_name, :registration, uniqueness: true
  validates :state_code, length: {is: 2}
  validate :check_cnpj


  def check_same_date_orders(order)
    self.orders.where(date: order.date).where(status: ["waiting", "negotiating"])
                                      .where.not(id: order.id).exists?
  end

  def average_rate
    return '' if rates.empty?
    self.rates.average(:score).round(1)
  end
  
  def check_cnpj
    cnpj = self.registration.gsub(/[^0-9]/, '')
    if cnpj.length != 14 || cnpj.chars.uniq.size == 1
      errors.add(:registration, 'não é valido')
    end

    pesos1 = [5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2]
    pesos2 = [6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2]

    soma1 = cnpj[0..11].chars.each_with_index.sum { |char, index| char.to_i * pesos1[index] }
    digito1 = soma1 % 11 < 2 ? 0 : 11 - (soma1 % 11)
    soma2 = cnpj[0..11].chars.each_with_index.sum { |char, index| char.to_i * pesos2[index] } + digito1 * pesos2[12]
    digito2 = soma2 % 11 < 2 ? 0 : 11 - (soma2 % 11)
    unless digito1 == cnpj[12].to_i && digito2 == cnpj[13].to_i
      errors.add(:registration, 'não é valido')
    end

  end

end

app/controllers/api/v1/buffets_controller.rb
class Api::V1::BuffetsController < ActionController::API
  def index
    if params[:search]
      @buffets = Buffet.where('brand_name LIKE ?', "%#{params[:search]}%").where(active: true)
    else
      @buffets = Buffet.where(active: true)
    end

    render json: @buffets.as_json(
                        only: [ :id, :brand_name, :city, :state_code, :description],
                        include: {payment_methods: {only: [:id], methods: :humanized_method_name }})
  end

  def show
    @buffet = Buffet.find_by(id: params[:id])

    return render status: 404 if @buffet.nil? || !@buffet.active?

    render json: @buffet.as_json(
                        only: [ :id, :brand_name, :phone_number, :email, :address,
                         :district, :city, :state_code, :zip_code, :description],
                         methods: :average_rate,
                         include: {payment_methods: {only: [:id], methods: [:humanized_method_name] }})
  end
end

app/controllers/buffets_controller.rb
class BuffetsController < ApplicationController
  before_action :set_buffet, only: [:show, :edit, :update, :disable, :activate]
  before_action :payment_methods, only: [:edit, :update, :new, :create]
  before_action :authenticate_buffet_owner!,  only: [:edit, :update, :new, :create, :disable]

  def index
    redirect_to current_buffet_owner.buffet if buffet_owner_signed_in?
    @buffets = Buffet.where(active: true)
  end

  def activate
    @buffet.update(active: true)
    redirect_to @buffet, notice: 'Buffet reativado com sucesso'
  end

  def disable
    @buffet.update(active: false)
    redirect_to @buffet, notice: 'Buffet desativado com sucesso'
  end

  def search
    @search = params[:query]
    category_value = EventCategory.revert_i18n(@search)
    @buffet = Buffet.find_by(brand_name: @search, active: true)
    return redirect_to @buffet if @buffet.present?
    @buffets = Buffet.left_outer_joins(events: :event_category )
              .where("buffets.brand_name LIKE ? OR buffets.city = ? OR event_categories.category = ?", 
              "%#{@search}%", @search, category_value).where(active: true).distinct.order('buffets.brand_name ASC')
  end

  def show
    @events = @buffet.events.where(active: true)
    @images = @buffet.holder_images
  end

  def edit; end

  def update
    payment_methods_ids = params[:buffet][:payment_method_ids].reject(&:blank?)
    if payment_methods_ids.any? && @buffet.update(buffet_params)
      @buffet.buffet_payment_methods.destroy_all
      set_payments_methods(payment_methods_ids)
    redirect_to @buffet, notice: 'Buffet atualizado com sucesso'
    else
      @buffet.errors.add(:payment_method_ids, "não pode ficar em branco") unless payment_methods_ids.any?
      flash.now[:alert] = "Erro ao atualizar Buffet"
      render :edit
    end
  end

  def new
    if current_buffet_owner.buffet.present?
      redirect_to current_buffet_owner.buffet, notice: 'Voce ja possui um buffet'
    end
    @buffet = Buffet.new
  end

  def create
    @buffet = Buffet.new(buffet_params)
    @buffet.buffet_owner = current_buffet_owner
    payment_methods_ids = params[:buffet][:payment_method_ids].reject(&:blank?)
    
    if payment_methods_ids.any? && @buffet.save
      set_payments_methods(payment_methods_ids)
      redirect_to @buffet, notice: "Buffet cadastrado com sucesso"
    else
      @buffet.errors.add(:payment_method_ids, "não pode ficar em branco") unless payment_methods_ids.any?
      flash.now[:alert] = "Erro ao cadastrar Buffet"
      render :new
    end
  end

  private
  def set_buffet
    @buffet = Buffet.find(params[:id])
    if buffet_owner_signed_in? && current_buffet_owner != @buffet.buffet_owner
      redirect_to current_buffet_owner.buffet, alert: 'Acesso não autorizado'
    end
  end

  def payment_methods
    @payment_methods = PaymentMethod.all
  end

  def set_payments_methods(ids)
    ids.each do |id|
      method = PaymentMethod.find(id)
      BuffetPaymentMethod.create!(buffet: @buffet, payment_method: method)
    end
  end

  def buffet_params
    params.require(:buffet).permit(:brand_name, :corporate_name, :registration, 
                                  :phone_number,:email, :address, :district,
                                  :city, :state_code, :zip_code,:description)
  end
end

app/views/buffets/_form.html.erb
<% if @buffet.errors.any? %>
  <article class="message">
    <div class="message-header">
      <p>Verifique os erros abaixo</p>
    </div>
    <div class="message-body">
      <ul>
        <% @buffet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </article>
<% end %>

<%= form_with(model: @buffet, local: true) do |f| %>
  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= f.label :brand_name, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <%= f.text_field :brand_name, class: "input" %>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= f.label :corporate_name, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <%= f.text_field :corporate_name, class: "input" %>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= f.label :registration, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <%= f.text_field :registration, class: "input" %>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= f.label :phone_number, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <%= f.text_field :phone_number, class: "input" %>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= f.label :email, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <%= f.email_field :email, class: "input" %>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= f.label :address, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <%= f.text_field :address, class: "input" %>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= f.label :district, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <%= f.text_field :district, class: "input" %>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= f.label :city, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <%= f.text_field :city, class: "input" %>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= f.label :state_code, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <%= f.text_field :state_code, class: "input" %>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= f.label :zip_code, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <%= f.text_field :zip_code, class: "input" %>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= f.label :description, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <%= f.text_area :description, class: "textarea" %>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= f.label :payment_methods, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field mt-1">
        <div class="control">
          <%= f.collection_check_boxes :payment_method_ids, @payment_methods, :id, :humanized_method_name do |box| %>
            <label class="checkbox ml-2">
              <%= box.check_box %>
              <%= box.text %>
            </label>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label">
    </div>
    <div class="field-body">
      <div class="field is-grouped">
        <div class="control">
          <%= f.submit class: "button is-link is-outlined" %>
        </div>
        <div class="control">
          <%= link_to 'Cancelar', root_path, class: "button is-light is-outlined" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/buffets/edit.html.erb
<div class="content">
  <h1 class="title" >Editar Buffet</h1>
  <%= render 'form' %>
</div>

app/views/buffets/index.html.erb
  <div class="content">
    <h1 class="title is-3">Buffets Registrados</h1>
    <div class="columns is-multiline">
      <% @buffets.each do |buffet| %>
        <div class="column is-one-third">
          <%= link_to buffet_path(buffet), class: 'box' do %>
            <dt class="title is-4"><%= buffet.brand_name %></dt>
            <dd class="subtitle is-6"><%= buffet.city %> | <%= buffet.state_code %></dd>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

app/views/buffets/new.html.erb
<div class="content">
  <h1 class="title" >Registrar buffet</h1>
  <%= render 'form' %>
</div>

app/views/buffets/search.html.erb
  <div class="content">
    <h1 class="title is-4">Resultados da Busca por: <%= @search %></h1>
    <p class="subtitle is-6"><%= @buffets.count %> buffet(s) encontrado(s)</p>

    <div class="columns is-multiline">
      <% @buffets.each do |buffet| %>
        <div class="column is-one-third">
          <div class="box">
            <p class="title is-5"><%= link_to buffet.brand_name, buffet_path(buffet), class: "has-text-primary" %></p>
            <p><%= buffet.city %>, <%= buffet.state_code %></p>
            <p><%= link_to "Ver detalhes", buffet_path(buffet), class: "button is-primary is-light mt-3" %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/buffets/show.html.erb
<div class="container">
  <div class="buttons is-grouped">
    <% if @buffet.buffet_owner == current_buffet_owner %>
      <%= link_to Buffet.human_attribute_name(:edit), edit_buffet_path(@buffet.id), class: "button is-link is-outlined" %>
      
      <% if @buffet.active? %>
        <%= button_to Buffet.human_attribute_name(:disable), disable_buffet_path(@buffet.id), method: :post, data: { confirm: 'Are you sure?' }, class: "button is-danger is-outlined" %>
      <% else %>
        <%= button_to Buffet.human_attribute_name(:activate), activate_buffet_path(@buffet.id), method: :post, class: "button is-success is-outlined" %>

      <% end %>
      
    <% else %>
      <%= link_to 'Voltar', buffets_path, class: "button is-warning is-outlined" %>
    <% end %>
  </div>
  <h1 class="title"><%= @buffet.brand_name %> <%= "(Desativado)" unless @buffet.active? %></h1>
  <div style="display: flex; align-items: center; margin-bottom: 5px">
    <progress class="progress is-warning is-small mb-0 mr-2" value="<%= @buffet.average_rate * 10 %>" max="50" style="max-width: 100px"></progress>
    <small>Avaliação média: <%= @buffet.average_rate  %></small>
  </div>
  <div class="box">
    <div class='columns' >
      <div class="column is-two-fifths">
        <div class="ml-5 content">
          <h4 class="title is-4">Detalhes do Buffet</h4>
          <div class="block ml-5 mt-5">
            <p>
              <% if @buffet.buffet_owner == current_buffet_owner %>
                <strong><%= Buffet.human_attribute_name(:corporate_name) %>:</strong> <%= @buffet.corporate_name %> <br>
              <% end %>
              <strong><%= Buffet.human_attribute_name(:registration) %>:</strong> <%= @buffet.registration %><br>
              <strong><%= Buffet.human_attribute_name(:phone_number) %>:</strong> <%= @buffet.phone_number %><br>
              <strong><%= Buffet.human_attribute_name(:email) %>:</strong> <%= @buffet.email %><br>
              <address>
                <strong><%= Buffet.human_attribute_name(:address) %>:</strong> <%= @buffet.address %><br>
                <strong><%= Buffet.human_attribute_name(:district) %>:</strong> <%= @buffet.district %><br>
                <strong><%= Buffet.human_attribute_name(:city) %>:</strong> <%= @buffet.city %><br>
                <strong><%= Buffet.human_attribute_name(:state_code) %>:</strong> <%= @buffet.state_code %><br>
                <strong><%= Buffet.human_attribute_name(:zip_code) %>:</strong> <%= @buffet.zip_code %><br>
              </address> <br>
              <strong><%= Buffet.human_attribute_name(:description) %>:</strong> <%= @buffet.description %><br>
              <strong>Métodos de Pagamento:</strong>
            </p>
            <ul>
              <% @buffet.payment_methods.each do |payment_method| %>
                <li><%= payment_method.humanized_method_name %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
      <div class='column'>
        <div class="content">
          <h4>Eventos disponiveis</h4>
          <% if @events.empty? %>
            Sem eventos cadastrados ainda <br>
            <%= link_to 'Criar novo evento', new_event_path, class: "button is-sucess is-outlined" if @buffet.buffet_owner == current_buffet_owner %>
          <% else %>
            <div class="grid" >
              <% @events.each do |event| %>
                <div class="cell">
                  <%= link_to event_path(event) do %>
                    <article class="media is-centered">  
                      <figure class="media-left">
                        <p class="image is-128x128">
                          
                          <% if event.cover_photo %>
                            <%= image_tag event.cover_photo.image, class: 'image' %>
                          <% else %>
                          <img src="https://bulma.io/assets/images/placeholders/128x128.png" />
                          <% end %>
                        </p>
                      </figure>  
                      <div class="media-content">                  
                        <div class='content'>
                          <span class="has-text-white"><%= event.name %></span> <br>
                          <p class='ml-3 has-text-grey is-italic is-size-7'>
                            <%= event.event_category.humanized_category_name %>
                            para <%= event.min_capacity %> pessoas <br>
                            Duração: <%= event.default_duration/60 %> horas <br>
                          </p>
                        </div>
                      </div>
                    </article>
                  <% end %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  
  </div>
</div>
<div class="container mt-5" > 
  <div class="box">
    <div class="columns" >
      <div class="column" >
        <div class='content' >
          <h2 class='subtitle is-5'> 
            Ultimas Avaliações
            <% if customer_signed_in? && current_customer.can_rate? %>
              <%= link_to Buffet.human_attribute_name(:rate), new_buffet_rate_path(@buffet), class: 'button is-light is-small is-outlined mb-2 ml-5' %> 
            <% end %>
            <%= link_to 'Ver mais', buffet_rates_path(@buffet),class: 'button is-light is-small is-outlined' %>
          </h2>
        </div>
        <div class="columns is-multiline" style="max-height: 315px; overflow-y: auto">
          <% @buffet.rates.last(3).each do |rate| %>
            <div class="column is-full">
              <%= link_to  buffet_rate_path(@buffet, rate) do %>
                <div class="box">
                  <p><%= rate.customer.email %></p>
                  <p><%= rate.comment %></p>
                    <div style="display: flex; align-items: center">
                      <progress class="progress is-warning is-small mb-0 mr-2" value="<%= rate.score * 10 %>" max="50" style="max-width: 100px"></progress>
                      <small>Nota: <%= rate.score %></small> <br>
                    </div>
                  
                  <small>Data: <%= I18n.localize(rate.rated_at, format: :short) %> </small>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="column is-7" >
        <div class='content' >
          <h2 class='subtitle is-5'> Imagens dos eventos </h2>
          <div class="columns is-multiline" style="max-height: 315px; overflow-y: auto">
            <% @images.each do |image| %>
              <div class="column is-one-quarter">
                <div class="card">
                  <div class="card-image">
                    <figure class="image is-4by3">
                      <%= image_tag image.image, alt: "Image" %>
                    </figure>
                  </div>
                  <div class="card-content">
                    <div class="content">
                      <p><%= image.holder.name %></p>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>