config/routes.rb
Rails.application.routes.draw do
  root to: 'buffets#index'
  
  devise_for :customers, controllers: {
    registrations: 'customers/registrations'
  }
  
  devise_for :buffet_owners

  resources :buffets, only: [:edit, :update, :show, :create, :new, :index] do
    resources :rates, only: [:show, :new, :create, :index]
    member do
      post :disable
      post :activate
    end
    get :search, on: :collection
  end

  resources :rates, only: [] do
    resources :holder_images, only: [:create]
  end

  resources :events, only: [:edit, :update, :show, :create, :new, :index] do
    resources :event_prices, only: [:edit, :update, :new, :create]
    resources :orders, only: [:new, :create]
    resources :holder_images, only: [:create, :destroy]
    member do
      post :disable
      post :activate
      post :cover
    end
  end

  resources :orders, only: [:show, :index] do
    resources :messages, only: [:create]
    resources :service_proposals, only: [:create, :update]
    member do
      post :accept_proposal
      post :reject_proposal
      post :cancel
    end
  end

  namespace :api do
    namespace :v1 do
      resources :buffets, only: [:show, :index] do
        resources :events, only: [:index] do
          get :availability, on: :member
        end
      end
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :buffet
  belongs_to :event_category
  belongs_to :cover_photo, class_name: 'HolderImage', optional: true, foreign_key: 'photo_id'

  has_many :holder_images, as: :holder, dependent: :destroy
  has_many :event_prices
  has_many :event_features
  has_many :features, through: :event_features
  has_many :orders

  validates :name, :description, :min_capacity, :max_capacity, :default_duration,
            :menu, presence: true
  
  validates :name, uniqueness: true

  def date_available?(date_string)
    date = Date.parse(date_string)
    return false if date <= Date.today
    proposals = buffet.orders.where(date: date).where(status: ['negotiating', 'confirmed'])
    return false if proposals.any?
    true
  end

  def capacity_available?(num_people)
    return num_people.to_i <= max_capacity
  end

  def set_features(ids)
    self.features.destroy_all
    ids.each do |id|
      feature = Feature.find(id)
      EventFeature.create!(event: self, feature: feature) unless feature.nil?
    end
  end
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < ActionController::API
  def index
    @buffet = Buffet.find_by(id: params[:buffet_id])
    @events = @buffet.events

    return render status: 404 if @events.nil?
    
    render json: @events.as_json(
                        only: [:id, :name, :description, :min_capacity, :max_capacity,
                        :default_duration, :menu, :exclusive_address],
                        include: {event_category: {only: [:id, :category]},
                                  features: {only: :id,
                                            methods: :humanized_feature_name },
                                  event_prices: {only: [:base_value, :extra_per_person, :extra_per_hour],
                                                methods: :humanized_price_name}})
  end

  def availability
    unless params[:date] && params[:num_people]
      return render status: 400, json: { error: 'Missing required parameters' }
    end
  
    @event = Event.find_by(id: params[:id])
    return render status: 404 if @event.nil? 
  
    unless @event.date_available?(params[:date])
      return render status: 200, json: {available: false, reason: "date is not available"}
    end
    
    unless @event.capacity_available?(params[:num_people])
      return render status: 200, json: {available: false, reason: "number of people exceed event limit"}
    end

    render status: 200, json: {available: true}
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_buffet_owner!, only: [:new, :create, :edit, :update]
  before_action :set_event, only: [:edit, :update, :show, :cover, :disable, :activate]
  before_action :set_lists, only: [:edit, :update, :new, :create]

  def disable
    @event.update(active: false)
    redirect_to @event, notice: 'Evento desativado com sucesso'
  end

  def activate
    @event.update(active: true)
    redirect_to @event, notice: 'Evento reativado com sucesso'
  end

  def cover
    unless params[:cover] && @event.holder_images.exists?(params[:cover])
      return redirect_to @event, alert: 'Imagem não encontrada' 
    end
    cover_photo = @event.holder_images.find(params[:cover])
    if @event.update(cover_photo: cover_photo)
      redirect_to @event, notice: 'Capa atualizada com sucesso'
    end
  end

  def index
    if buffet_owner_signed_in?
      @events = current_buffet_owner.buffet.events
    else
      redirect_to root_path
    end
  end

  def edit; end

  def update
    feature_ids = params[:event][:feature_ids].reject(&:blank?)
    if @event.update(event_params)
      @event.set_features(feature_ids)
      redirect_to @event, notice: "Evento atualizado com sucesso"
    else
      flash.now[:alert] = "Erro ao atualizar evento"
      render :edit
    end
  end

  def show; end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.buffet = current_buffet_owner.buffet
    feature_ids = params[:event][:feature_ids].reject(&:blank?)
    if @event.save
      @event.set_features(feature_ids)
      redirect_to @event, notice: "Evento cadastrado com sucesso"
    else
      flash.now[:alert] = "Erro ao cadastrar evento"
      render :new
    end
  end

  private
  def event_params
    params.require(:event).permit(:name, :description, :min_capacity,
                                  :max_capacity, :default_duration,
                                  :menu, :event_category_id, :exclusive_address,
                                  imageable_images_attributes: [:image, :user_id])
  end

  def set_event
    @event = Event.find(params[:id])
    if buffet_owner_signed_in? && current_buffet_owner != @event.buffet.buffet_owner
      redirect_to current_buffet_owner.buffet, alert: 'Acesso não autorizado'
    end
  end

  def set_lists
    @features = Feature.all
    @event_categories = EventCategory.all
  end

end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
  <article class="message">
    <div class="message-header">
      <p>Verifique os erros abaixo</p>
    </div>
    <div class="message-body">
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </article>
<% end %>

<%= form_with(model: @event) do |f| %>
  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= f.label :event_category_id, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <%= f.collection_select :event_category_id, @event_categories, :id, :humanized_category_name, { prompt: "Selecione o tipo de evento" }, { class: "input" } %>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= f.label :name, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <%= f.text_field :name, class: "input" %>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= f.label :min_capacity, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <%= f.number_field :min_capacity, class: "input" %>
        </div>
      </div>

      <div class="field">
        <div class="field is-horizontal ">
          <div class="field-label is-normal">
            <%= f.label :max_capacity, class: "label" %>
          </div>
          <div class="field-body">
            <div class="field">
              <div class="control">
                <%= f.number_field :max_capacity, class: "input" %>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <div class="field">
        <div class="field is-horizontal">
          <div class="field-label is-normal">
            <%= f.label :default_duration, class: "label" %>
          </div>
          <div class="field-body">
            <div class="field">
              <div class="control">
                <%= f.number_field :default_duration, class: "input" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= f.label :description, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <%= f.text_area :description, class: "textarea" %>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= f.label :menu, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <%= f.text_area :menu, class: "textarea" %>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= f.label :exclusive_address, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <label class="radio">
            <%= f.radio_button :exclusive_address, true %> Sim
          </label>
          <label class="radio">
            <%= f.radio_button :exclusive_address, false, checked: true %> Não
          </label>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= f.label :features, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field mt-1">
        <div class="control">
          <%= f.collection_check_boxes :feature_ids, @features, :id, :humanized_feature_name do |box| %>
            <label class="checkbox ml-2">
              <%= box.check_box %>
              <%= box.text %>
            </label>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-grouped">
    <div class="field-label" >
    </div>
    <div class="field-body" >
      <div class="control mr-2">
        <%= f.submit class: "button is-link is-outlined" %>
      </div>
      <div class="control">
        <%= link_to 'Cancelar', root_path, class: "button is-warning is-outlined" %>
      </div>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
  <div class="container">
    <h1 class="subtitle">Editar evento</h1>
    <%= render 'form' %>
  </div>

app/views/events/index.html.erb
  <div class="container">
    <h1 class="title">Eventos Disponíveis</h1>
    <% if @events.empty? %>
      <p>Sem eventos cadastrados ainda</p>
      <%= link_to 'Criar novo evento', new_event_path, class: 'button is-link' %>
    <% else %>
      <div class="columns is-multiline">
        <% @events.each do |event| %>
          <div class="column is-one-third">
            <div class="card">
              <div class="card-image">
                <figure class="image is-4by3">
                  <% if event.cover_photo %>
                    <%= image_tag event.cover_photo.image, class: 'image' %>
                  <% else %>
                    <img src="https://bulma.io/assets/images/placeholders/128x128.png" />
                  <% end %>
                </figure>
              </div>
              <div class="card-content">
                <p class="title is-4">
                  <%= link_to event.name, event_path(event), class: 'has-text-primary' %>
                  <%= "(Desativado)" unless event.active? %>
                </p>
                <p class="subtitle is-6"><%= event.event_category.humanized_category_name %></p>
                <div class="content">
                  <p>Para <%= event.min_capacity %> pessoas</p>
                  <p>Duração: <%= event.default_duration / 60 %> horas</p>
                </div>
              </div>
              <footer class="card-footer">
                <%= link_to 'Ver detalhes', event_path(event), class: 'card-footer-item' %>
              </footer>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

app/views/events/new.html.erb
  <div class="container">
    <h1 class="subtitle">Cadastrar novo evento</h1>
    <%= render 'form' %>
  </div>

app/views/events/show.html.erb
<div class="content">
  <%= link_to "Retornar para #{@event.buffet.brand_name}", @event.buffet, class:"button is-rounded is-small is-outlined is-danger is-light" %>
</div>

<div class="box">
  <div class='columns'>
    
    <div class='column is-one-third'>
      <h1 class="title"><%= @event.name %> <%= "(Desativado)" unless @event.active? %></h1>
      <p class="subtitle"><%= "Tipo de evento: " + @event.event_category.humanized_category_name %></p>
      <address>
        <p><strong>Capacidade:</strong> mínimo <%= @event.min_capacity %> e máximo <%= @event.max_capacity %></p>
        <p><strong>Duração:</strong> <%= @event.default_duration / 60 %> horas</p>
        <p><strong>Descrição:</strong> <%= @event.description %></p>
        <p><strong>Menu:</strong> <%= @event.menu %></p>
        <p><strong>Endereço Exclusivo:</strong> <%= @event.exclusive_address ? "Sim" : "Não" %></p>
      </address>
      <div class="content">
        <p><strong>Características:</strong></p>
        <ul>
          <% @event.features.each do |f| %>
            <li class="subtitle is-6"><%= f.humanized_feature_name %></li>
          <% end %>
        </ul>
      </div>
      <hr>
      <% if buffet_owner_signed_in? && @event.buffet.buffet_owner == current_buffet_owner %>
        <div class='buttons is-grouped'>
          <%= link_to Event.human_attribute_name(:edit), edit_event_path(@event.id), class:"button is-rounded is-warning is-outlined" %>
          <% if @event.active? %>
            <%= button_to Event.human_attribute_name(:disable), disable_event_path(@event.id), method: :post, class:"button is-rounded is-danger is-outlined" %>
          <% else %>
            <%= button_to Event.human_attribute_name(:activate), activate_event_path(@event.id), method: :post, class:"button is-rounded is-success is-outlined" %>
          <% end %>
        </div>
        <div class="buttons is-grouped">
          <%= link_to 'Definir preço padrão', new_event_event_price_path(@event, price_type: 'standard'),
                        class:"button is-rounded is-info is-outlined" unless @event.event_prices.exists?(price_type: 'standard') %>
          <%= link_to 'Definir preço especial',new_event_event_price_path(@event, price_type: 'special'), 
                        class:"button is-rounded is-primary is-outlined" unless @event.event_prices.exists?(price_type: 'special') %>
        </div>
      <% elsif customer_signed_in? %>
        <div class='control'>
          <%= link_to 'Criar um pedido', new_event_order_path(@event.id), class: "button is-rounded is-link is-outlined" %>
        </div>
      <% end %>
    </div>
    <% if @event.event_prices.any? %>
      <% @event.event_prices.each do |price| %>
        <div class='column is-one-third'>
          <div class="card my-3">
            <div class="card-content">
              <p class="title is-5"><%= price.humanized_price_name %></p>
              <div class="content">
                <p><span>Valor base: <%= number_to_currency(price.base_value) %></span></p>
                <p><span>Adicional por pessoa: <%= number_to_currency(price.extra_per_person) %></span></p>
                <p><span>Adicional por hora: <%= number_to_currency(price.extra_per_hour) %></span></p>
                <% if buffet_owner_signed_in? && current_buffet_owner.buffet == @event.buffet %>
                  <%= link_to "Atualizar #{price.humanized_price_name}", edit_event_event_price_path(@event, price), class: "button is-rounded is-info is-outlined mt-3" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="box">
  <h2 class="title is-3">Galeria de Imagens</h2>
  <% if buffet_owner_signed_in? && current_buffet_owner.buffet == @event.buffet %>
    <%= form_with(model: [@event, HolderImage.new], html: { class: 'field is-horizontal' }) do |form| %>
      <div class="field is-horizontal">
        <div class="field-body">
          <div class="field">
            <div class="control">
              <div class="file has-name">
                <label class="file-label">
                  <%= form.file_field :image, accept: 'image/png, image/jpeg, image/jpg',
                                              class: 'file-input', id: 'file-input' %>
                  <span class="file-cta">
                    <span class="file-icon">
                      <i class="fas fa-upload"></i>
                    </span>
                    <span class="file-label">
                      Escolha um arquivo…
                    </span>
                  </span>
                  <span class="file-name" id="file-name">
                    Nenhum arquivo selecionado
                  </span>
                </label>
              </div>
            </div>
          </div>
          <div class="field">
            <div class="control">
              <%= form.submit class: 'button is-primary' %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="columns is-multiline mt-5">
    <% @event.holder_images.each do |image| %>
      <div class="column is-one-quarter" style="<%= "border: 1px solid white; border-radius: 10px " if @event.cover_photo == image %>">
        <div class="box-<%=image.id%>">
          <figure class="image is-4by4">
            <%= image_tag image.image, class: 'image' %>
          </figure>
          <% if buffet_owner_signed_in? && current_buffet_owner.buffet == @event.buffet %>
            <div class="has-text-centered">
              <div class="buttons mt-2" >
                <%= button_to 'Remover', event_holder_image_path(@event, image), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-danger is-small is-outlined' %>
                <% if @event.cover_photo != image %>
                  <%= button_to 'Definir como capa', cover_event_path(cover: image.id), method: :post, class: 'button is-info is-small is-outlined' %>
                <% else %>
                  <p class= 'button is-info is-small is-outlined'>Capa atual</p>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    const fileInput = document.getElementById('file-input');
    const fileName = document.getElementById('file-name');

    fileInput.addEventListener('change', () => {
      const file = fileInput.files[0];
      if (file) {
        fileName.textContent = file.name;
      } else {
        fileName.textContent = 'Nenhum arquivo selecionado';
      }
    });
  });
</script>