config/routes.rb
Rails.application.routes.draw do
  root to: 'buffets#index'
  
  devise_for :customers, controllers: {
    registrations: 'customers/registrations'
  }
  
  devise_for :buffet_owners

  resources :buffets, only: [:edit, :update, :show, :create, :new, :index] do
    resources :rates, only: [:show, :new, :create, :index]
    member do
      post :disable
      post :activate
    end
    get :search, on: :collection
  end

  resources :rates, only: [] do
    resources :holder_images, only: [:create]
  end

  resources :events, only: [:edit, :update, :show, :create, :new, :index] do
    resources :event_prices, only: [:edit, :update, :new, :create]
    resources :orders, only: [:new, :create]
    resources :holder_images, only: [:create, :destroy]
    member do
      post :disable
      post :activate
      post :cover
    end
  end

  resources :orders, only: [:show, :index] do
    resources :messages, only: [:create]
    resources :service_proposals, only: [:create, :update]
    member do
      post :accept_proposal
      post :reject_proposal
      post :cancel
    end
  end

  namespace :api do
    namespace :v1 do
      resources :buffets, only: [:show, :index] do
        resources :events, only: [:index] do
          get :availability, on: :member
        end
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchBuffet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  </head>
  <body>
    <nav class="navbar is-dark has-shadow" role="navigation" aria-label="main navigation" id="navbar">
  <div class="navbar-brand">
    <div class="navbar-item is-size-3">
      <%= link_to 'Cade Buffet?', root_path, class: "has-text-white" %>
    </div>
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarMenu">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarMenu" class="navbar-menu">
    <div class="navbar-start">
      <% if buffet_owner_signed_in? %>
        <div class="navbar-item">
          <% if current_buffet_owner.buffet.nil? %>
            <%= link_to 'Meu Buffet', new_buffet_path, class:"button is-ghost has-text-light" %>
          <% else %>
            <%= link_to 'Meu Buffet', current_buffet_owner.buffet, class:"button is-ghost has-text-light" %>
          <% end %>
          <%= link_to 'Anunciar Evento', new_event_path, class:"button is-ghost has-text-light" %>
          <%= link_to 'Lista de Eventos', events_path, class:"button is-ghost has-text-light" %>
          <%= link_to 'Pedidos', orders_path, class:"button is-ghost has-text-light" %>
        </div>
      <% else %>
        <div class="navbar-item">
          <%= form_with(url: search_buffets_path, method: :get, class: "field has-addons") do |f| %>
            <div class="control is-expanded">
              <%= f.text_field :query, placeholder: 'Buscar Buffet', class: 'input' %>
            </div>
            <div class="control">
              <%= f.submit 'Buscar', class: 'button is-white is-outlined' %>
            </div>
          <% end %>
        </div>
        <% if customer_signed_in? %>
          <div class="navbar-item">
            <%= link_to 'Meus pedidos', orders_path, class:"button is-ghost has-text-light" %>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <p class="mr-2">
          <%= "Dono de Buffet: #{current_buffet_owner.email}" if buffet_owner_signed_in? %>
          <%= "Cliente: #{current_customer.email}" if customer_signed_in? %>
        </p>
        <div class="buttons">
          <% if buffet_owner_signed_in? %>
            <%= button_to 'Sair', destroy_buffet_owner_session_path, method: :delete, class:"button is-warning" %>
          <% elsif customer_signed_in? %>
            <%= button_to 'Sair', destroy_customer_session_path, method: :delete, class:"button is-warning" %>
          <% else %>
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link is-arrowless">Para empresas</a>
              <div class="navbar-dropdown is-boxed" id="owners">
                <%= link_to 'Logar', new_buffet_owner_session_path, class: "navbar-item" %>
                <%= link_to 'Registrar-se', new_buffet_owner_registration_path, class: "navbar-item" %>
              </div>
            </div>
            <div class="field is-grouped" id="customers">
              <%= link_to 'Logar', new_customer_session_path, class: "button is-primary" %>
              <%= link_to 'Registrar-se', new_customer_registration_path, class: "button is-light" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>


  <% if notice %>
    <div class="notification is-success">
      <button class="delete" onclick="this.parentElement.style.display='none';" ></button>
      <%= notice %>
    </div>  
  <% end %>
    
  <% if alert %>
    <div class="notification is-danger">
      <button class="delete" onclick="this.parentElement.style.display='none';" ></button>
      <%= alert %>
    </div>
  <% end %>
  <section class="section">
    <%= yield %>
  </section>
  </body>
</html>